version: '3.8'
services:
  catalina:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:3000"
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - NODE_ENV=production
    volumes:
      - ./public/uploads:/app/public/uploads